name: Component Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  component_visual_regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Change directory to nuxt-app
        run: |
          cd nuxt-app

      - name: Install dependencies
        run: |
          npm install
        working-directory: nuxt-app

      - name: Build Storybook
        run: |
          npm run build-storybook
        working-directory: nuxt-app

      - name: Publish to Chromatic
        run: |
          npx chromatic --project-token=chpt_356f336c2d7b42f --exit-zero-on-changes
        working-directory: nuxt-app
